# Generated by Django 4.2 on 2024-10-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DosageSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='medications/')),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('medications', models.ManyToManyField(blank=True, related_name='treatments', to='Medication.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medications', models.ManyToManyField(related_name='prescriptions', through='Medication.DosageSchedule', to='Medication.medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.ManyToManyField(blank=True, related_name='medications', to='Medication.sideeffect'),
        ),
        migrations.AddField(
            model_name='dosageschedule',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medication.medication'),
        ),
        migrations.AddField(
            model_name='dosageschedule',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medication.prescription'),
        ),
    ]
