# Generated by Django 4.2 on 2024-10-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medications',
        ),
        migrations.DeleteModel(
            name='DosageSchedule',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
