# Generated by Django 4.2 on 2024-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
