# Generated by Django 5.1.2 on 2024-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='severity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
